backend:
  name: github
  repo: eddie484/eddie484.github.io
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - label: Category
        name: category
        widget: select
        options:
          - { label: 프로젝트, value: projects }
          - { label: customISA to DOOM, value: customisa2doom }
          - { label: 일지, value: journal }
          - { label: 게임, value: games }
          - { label: 게임A, value: game-a }
          - { label: 게임B, value: game-b }
          - { label: 게임C, value: game-c }
          - { label: 잡생각, value: thoughts }
          - { label: 식사, value: food }
      - { name: pubDate, label: Publish Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
